name: Packaged crate

on:
  workflow_call:

permissions: {}

jobs:
  packaged-crate:
    name: packaged crate
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      - uses: ./.github/actions/setup-rust
      - run: bash ci/check-packaged-crate.sh
