name: Public docs

on:
  workflow_call:

permissions: {}

jobs:
  public-docs:
    name: public docs
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: ./.github/actions/setup-rust
        with:
          targets: wasm32-unknown-unknown
      - run: bash ci/check-public-docs.sh
