name: Public docs

on:
  workflow_call:

permissions: {}

jobs:
  public-docs:
    name: public docs
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      - uses: ./.github/actions/setup-rust
        with:
          targets: wasm32-unknown-unknown
      - run: bash ci/check-public-docs.sh
